# GitHub Actions 下载脚本配置
dir_rule:
  base_dir: ${JM_DOWNLOAD_DIR}
  rule: Bd_Aauthor_Atitle_Pindex

client:
  impl: api
  domain: [
    "www.jmapinode1.cc",
    "www.jmapinode2.cc",
    "www.jmapinode3.cc",
    "www.jmapibranch2.cc"
  ]

# 插件配置
plugin:
  after_init:
    - plugin: usage_log # 实时打印硬件占用率的插件
      kwargs:
        interval: 0.5 # 间隔时间
        enable_warning: false # 不告警
