site_name: jmcomic
theme:
  name: mkdocs
  highlightjs: true
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: primary
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          paths: [ '../../src/' ]
          options:
            docstring_style: sphinx


markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition

docs_dir: sources