site_name: jmcomic
theme:
  name: material
  highlightjs: true
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: primary
  features:
    - content.code.copy
    - content.code.select
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          paths: [ '../../src/' ]
          options:
            docstring_style: sphinx


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

docs_dir: sources