name: 下载JM本子

on:
  push:
    branches: [ 'workflow', 'workflow_local' ]
    paths:
      - '.github/workflows/*.yml' # 工作流定义
      - 'usage/**/*.py' # 工作流脚本
      - 'assets/config/*.yml' # option配置文件
      - 'src/**/*.py' # 源码

  pull_request:
    branches: [ 'workflow', 'workflow_local' ]

jobs:
  crawler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 安装依赖项（pip）
        if: ${{ github.ref == 'refs/heads/workflow' }}
        run: |
          python -m pip install --upgrade pip
          pip install jmcomic -i https://pypi.org/project --upgrade

      - name: 安装依赖项（local）
        if: ${{ github.ref == 'refs/heads/workflow_local' }}
        run: |
          python -m pip install --upgrade pip
          pip install commonX -i https://pypi.org/project --upgrade
          pip install -e ./

      - name: 安装依赖项（pull_request）
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          python -m pip install --upgrade pip
          pip install commonX -i https://pypi.org/project --upgrade
          pip install -e ./

      - name: 运行下载脚本
        env:
          JM_USERNAME: ${{ secrets.JM_USERNAME }}
          JM_PASSWORD: ${{ secrets.JM_PASSWORD }}
        run: |
          mkdir -p /home/runner/work/jmcomic/download/
          cd ./usage/
          python workflow_download.py

      - name: 压缩下载的漫画
        run: |
          cd /home/runner/work/jmcomic/download/
          tar -zcvf ../下载完成的本子.tar.gz ./

      - name: 上传结果
        uses: actions/upload-artifact@v3
        with:
          name: 下载完成的本子
          path: /home/runner/work/jmcomic/下载完成的本子.tar.gz
          if-no-files-found: warn
          retention-days: 90
