name: 发布PYPI

on:
  release:
    types: [ published ]

jobs:
  release:
    name: 构建并发布 jmcomic 到 PyPI
    runs-on: ubuntu-latest
    steps:
      - name: 切换到master分支
        run: git checkout master

      - name: Set up Python 3.7
        uses: actions/setup-python@v3
        with:
          python-version: "3.7"

      - name: 构建模块
        run: |
          python -m pip install build
          python -m build

      - name: 发布PYPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_JMCOMIC }}
